create sequence article_seq start with 1 increment by 50;
create sequence location_seq start with 1 increment by 50;
create sequence media_seq start with 1 increment by 50;
create sequence tag_seq start with 1 increment by 50;
create table article (latitude numeric(2,9) not null, longitude numeric(2,9) not null, id bigint not null, location_id bigint not null, name varchar(255) not null, primary key (id));
create table location (latitude numeric(2,9) not null, longitude numeric(2,9) not null, id bigint not null, title varchar(255) not null, primary key (id));
create table location_tags (location_id bigint not null, tags_id bigint not null, primary key (location_id, tags_id));
create table media (article_id bigint, id bigint not null, location_id bigint, external_media_id varchar(255) not null, type varchar(255) check (type in ('audio','image')), primary key (id));
create table tag (id bigint not null, value varchar(255) unique, primary key (id));
create table tag_locations (locations_id bigint not null, tag_id bigint not null, primary key (locations_id, tag_id));
create index coordinate_idx on location (longitude, latitude);
alter table if exists article add constraint FK91frh4mcqgsww0hmlui8730uc foreign key (location_id) references location;
alter table if exists location_tags add constraint FKa79891tf7051pf5mvoy1og6v0 foreign key (tags_id) references tag;
alter table if exists location_tags add constraint FKx4w843d9hmea37c6ejbp5agh foreign key (location_id) references location;
alter table if exists media add constraint FK92sbocgjb2ewti4xnp20hc7jv foreign key (article_id) references article;
alter table if exists media add constraint FK2f2gcqy96hw6jyi9so23ftdr6 foreign key (location_id) references location;
alter table if exists tag_locations add constraint FKtks0ymbdehk84hvjgcgljtjau foreign key (locations_id) references location;
alter table if exists tag_locations add constraint FK44akqd9bleopo675jho1oclr3 foreign key (tag_id) references tag;
create sequence article_seq start with 1 increment by 50;
create sequence location_seq start with 1 increment by 50;
create sequence media_seq start with 1 increment by 50;
create sequence tag_seq start with 1 increment by 50;
create table article (latitude numeric(2,9) not null, longitude numeric(2,9) not null, id bigint not null, location_id bigint not null, name varchar(255) not null, primary key (id));
create table location (latitude numeric(2,9) not null, longitude numeric(2,9) not null, id bigint not null, title varchar(255) not null, primary key (id));
create table location_tags (location_id bigint not null, tags_id bigint not null, primary key (location_id, tags_id));
create table media (article_id bigint, id bigint not null, location_id bigint, external_media_id varchar(255) not null, type varchar(255) check (type in ('audio','image')), primary key (id));
create table tag (id bigint not null, value varchar(255) unique, primary key (id));
create table tag_locations (locations_id bigint not null, tag_id bigint not null, primary key (locations_id, tag_id));
create index coordinate_idx on location (longitude, latitude);
alter table if exists article add constraint FK91frh4mcqgsww0hmlui8730uc foreign key (location_id) references location;
alter table if exists location_tags add constraint FKa79891tf7051pf5mvoy1og6v0 foreign key (tags_id) references tag;
alter table if exists location_tags add constraint FKx4w843d9hmea37c6ejbp5agh foreign key (location_id) references location;
alter table if exists media add constraint FK92sbocgjb2ewti4xnp20hc7jv foreign key (article_id) references article;
alter table if exists media add constraint FK2f2gcqy96hw6jyi9so23ftdr6 foreign key (location_id) references location;
alter table if exists tag_locations add constraint FKtks0ymbdehk84hvjgcgljtjau foreign key (locations_id) references location;
alter table if exists tag_locations add constraint FK44akqd9bleopo675jho1oclr3 foreign key (tag_id) references tag;
create sequence article_seq start with 1 increment by 50;
create sequence location_seq start with 1 increment by 50;
create sequence media_seq start with 1 increment by 50;
create sequence tag_seq start with 1 increment by 50;
create table article (latitude numeric(2,9) not null, longitude numeric(2,9) not null, id bigint not null, location_id bigint not null, name varchar(255) not null, primary key (id));
create table location (latitude numeric(2,9) not null, longitude numeric(2,9) not null, id bigint not null, title varchar(255) not null, primary key (id));
create table location_tags (location_id bigint not null, tags_id bigint not null, primary key (location_id, tags_id));
create table media (article_id bigint, id bigint not null, location_id bigint, external_media_id varchar(255) not null, type varchar(255) check (type in ('audio','image')), primary key (id));
create table tag (id bigint not null, value varchar(255) unique, primary key (id));
create table tag_locations (locations_id bigint not null, tag_id bigint not null, primary key (locations_id, tag_id));
create index coordinate_idx on location (longitude, latitude);
alter table if exists article add constraint FK91frh4mcqgsww0hmlui8730uc foreign key (location_id) references location;
alter table if exists location_tags add constraint FKa79891tf7051pf5mvoy1og6v0 foreign key (tags_id) references tag;
alter table if exists location_tags add constraint FKx4w843d9hmea37c6ejbp5agh foreign key (location_id) references location;
alter table if exists media add constraint FK92sbocgjb2ewti4xnp20hc7jv foreign key (article_id) references article;
alter table if exists media add constraint FK2f2gcqy96hw6jyi9so23ftdr6 foreign key (location_id) references location;
alter table if exists tag_locations add constraint FKtks0ymbdehk84hvjgcgljtjau foreign key (locations_id) references location;
alter table if exists tag_locations add constraint FK44akqd9bleopo675jho1oclr3 foreign key (tag_id) references tag;