create sequence article_seq start with 1 increment by 1;
create sequence location_seq start with 1 increment by 1;
create sequence media_seq start with 1 increment by 1;
create sequence tag_seq start with 1 increment by 1;
create table article (id bigint not null, location_id bigint not null, name varchar(255) not null, coordinates geometry(Point,4326) not null, primary key (id));
create table location (id bigint not null, title varchar(255) not null, coordinates geometry(Point,4326) not null, primary key (id));
create table location_tag (location_id bigint not null, tag_id bigint not null, primary key (location_id, tag_id));
create table media (article_id bigint, id bigint not null, location_id bigint, external_media_id varchar(255) not null, type varchar(255) check (type in ('audio','image')), primary key (id));
create table tag (id bigint not null, value varchar(255) unique, primary key (id));
alter table if exists article add constraint FK91frh4mcqgsww0hmlui8730uc foreign key (location_id) references location;
alter table if exists location_tag add constraint FK3v8cy6pwhs2ful50h2jirsx2g foreign key (location_id) references location;
alter table if exists location_tag add constraint FKgrpnco0g0npewc87e8he3oj5w foreign key (tag_id) references tag;
alter table if exists media add constraint FK92sbocgjb2ewti4xnp20hc7jv foreign key (article_id) references article;
alter table if exists media add constraint FK2f2gcqy96hw6jyi9so23ftdr6 foreign key (location_id) references location;
create index location_coordinates_ind ON location USING GIST ( coordinates );
create index article_coordinates_ind ON article USING GIST ( coordinates );